name = "biscotto"
version = "1.0.0"
description = "A library for storing cookies in a jar and sending them with HTTP requests."
licences = ["MIT"]
repository = { type = "github", user = "peonii", repo = "biscotto" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
